[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_twitter = "GUsNRWuXCaf5s24AcisHGtxjgVWAJRuwx9P9YsNK1r84"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/Fluture/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
